### ISSUE TITLE
Watlerschell please send me GstHid repository

### ISSUE THREAD

**Issue by MrKsiJ** [walterschell/Lua#19]
I'm writing a driver for Dualshock 4 so that you can play sound from the gamepad from the sbc file you had a GstHid repository on github, but now it's not there, if you have it left on your computer, can you send it to me please

P.S.
Since the system of private messages on github has been cut, I am writing to you in issues here

**Comment by walterschell** [comment]
I’m sorry I don’t recognize that repo. Would you mind sending me where you found reference to it so I can jog my memory?

**Comment by MrKsiJ** [comment]
> I’m sorry I don’t recognize that repo. Would you mind sending me where you found reference to it so I can jog my memory?

https://github.com/WatlerSchell/GstHid

**Comment by MrKsiJ** [comment]
> 
This link is always provided to me by ChatGPT when I try to create a slnik object using Gst Hid.DeviceSink
I don't understand where he got this information from, but the link leads to your non-existing repository, I don't know if it existed before, but you decided to delete it

**Comment by MrKsiJ** [comment]
It would be cool if you still have this library, it would help me to finally make sound transmission on Windows on the Dualshock 4 gamepad to use this feature in my game

**Comment by walterschell** [comment]
That definitely looks like a case of ChatGPT inventing a reference. I don't remember ever having that repo.

**Comment by MrKsiJ** [comment]
> That definitely looks like a case of ChatGPT inventing a reference. I don't remember ever having that repo.

sounds sad

**Comment by MrKsiJ** [comment]
well, okay, I'm going to look for another way to do it, thanks, success)
