### ISSUE TITLE
Unable to build as cmake subproject + EASY FIX

### ISSUE THREAD

**Issue by mengler-tomas** [walterschell/Lua#29]
There is a problem adding this project as a subproject.

Problem + solution:
There is a line in CMakeLists.txt in the root directory
`add_subdirectory(lua-${CMAKE_PROJECT_VERSION})`
which is meant to add a specific version of lua.
Which would be fine if it wasn't using the version value from the top-level project
To solve this problem, all you have to do is change CMAKE_PROJECT_VERSION to PROJECT_VERSION

CMAKE_PROJECT_VERSION is version of **top-level project**. (This causes it to build normally when this project is not a subproject)
PROJECT_VERSION is version of **current project**.

**Comment by konradx64** [comment]
Thanks!
